chore: minor tweaks

diff --git a/command-chain/desktop-launch b/command-chain/desktop-launch
--- a/command-chain/desktop-launch
+++ b/command-chain/desktop-launch
@@ -27,6 +27,20 @@ function wait_for_async_execs() {
   done
 }
 
+# runtime snap name declared in consumer's snapcraft environment
+RUNTIME_NAME="qt6-core24"
+
+# exit as early if the content snap is not connected
+if ! snapctl is-connected $RUNTIME_NAME; then
+  echo -e "ERROR: snap $SNAP_NAME is not connected to the $RUNTIME_NAME content interface.\n"
+  echo -e "Run these commands to make sure required content interface is installed & connected:\n\n"
+
+  echo -e "snap install $RUNTIME_NAME\n"
+  echo -e "snap connect $SNAP_NAME:$RUNTIME_NAME $RUNTIME_NAME\n"
+
+  exit 1
+fi
+
 # shellcheck source=/dev/null
 source "$SNAP_USER_DATA/.last_revision" 2>/dev/null || true
 if [ "$SNAP_DESKTOP_LAST_REVISION" = "$SNAP_REVISION" ]; then
@@ -140,11 +154,6 @@ function is_subpath() {
   parent="$(realpath "$2")"
   [ "${dir##"${parent}"/}" != "${dir}" ] && return 0 || return 1
 }
-
-if ! snapctl is-connected "qt-framework-6-6-core22"; then
-  echo "ERROR: not connected to the qt-framework-6-6-core22 content interface."
-  exit 1
-fi
 
 # Use keyfile storage if gsettings isn't accessible
 if ! snapctl is-connected gsettings 2>/dev/null; then
@@ -597,6 +606,9 @@ append_dir QTWEBENGINEPROCESS_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/qt$QT_SE
 # of the system Compose files
 export QTCOMPOSE="$SNAP_DESKTOP_RUNTIME/usr/share/X11/locale"
 export QT_XKB_CONFIG_ROOT="/usr/share/X11/xkb"
+
+# Add path to VLC plugins
+export VLC_PLUGIN_PATH="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/vlc/plugins"
 
 # Ensure QtChooser behaves.
 export QTCHOOSER_NO_GLOBAL_DIR=1
